package edu.brown.cs.websocket;

/**
 * Enums for Messages to be sent to and from front-end.
 *
 */
public enum MESSAGE_TYPE {
	CONNECT, LOGIN, SIGNUP, MOVE, HEARTBEAT, FORWARD, GUEST, ERROR, GAME_START, GAME_ACTION, GAME_LEAVE, LOGOUT, CANBUY, SHOP, BUY, ROCKET_CHANGE, JOIN_ARENA, LEAVE_ARENA, LOBBY_CREATE, LOBBY_LEAVE, LOBBY_INVITE, LOBBY_LOAD_GAME, INVITE_RESPONSE, RANDOM_OPPONENT, CHANGEUSER, CHANGEPASS, UPDATESCORE
}
